dist: bionic
language: go
go:
  - 1.14

env:
  - GO111MODULE=on

branches:
  except:
    - gh-pages

addons:
  apt:
    packages:
      - zsh

install:
  - bundle install --jobs 4 --retry 3 --path rbvendor/bundle
  - go mod download

script:
  - go test ./...
  - script/build
  - bundle exec cucumber -s --tags=~@wip

before_cache:
  - bundle clean

cache:
  directories:
    - rbvendor/bundle
    - $GOPATH/pkg/mod
